<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3tr3f3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3tr3f3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX3tr3f3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX3tr3f3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX3tr3f3\appProdProjectContainer([
    'container.build_hash' => 'X3tr3f3',
    'container.build_id' => 'd6f1431f',
    'container.build_time' => 1584068659,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX3tr3f3');
